services:
  job-migrator:
    build: .
    container_name: job_migrator_worker
    env_file:
      - .env
    networks:
      - backend
    # El CMD ya está en el Dockerfile, pero aquí lo sobreescribimos para compatibilidad
    command: ./migrator
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.migrator-daily.schedule: "0 30 4 * * *"
      ofelia.job-exec.migrator-daily.command: "./migrator"
      ofelia.job-exec.migrator-daily.no-overlap: "true"

    image: job-migrator-image

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: job_scheduler
    depends_on:
      - job-migrator
    env_file:
      - .env
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend